#!/usr/bin/env python3
import argparse
import concurrent.futures
import json
import pathlib
import threading

from common import load_config, progress, read_jsonl, rel, run, write_text


def output_layout(cfg: dict) -> str:
    layout = cfg.get("cmake_output_layout", "centralized")
    if layout not in {"centralized", "beside_mk"}:
        raise SystemExit(f"unsupported cmake_output_layout: {layout}")
    return layout


def cmake_output_for_target(cfg: dict, target: dict) -> pathlib.Path:
    if output_layout(cfg) == "centralized":
        return pathlib.Path(cfg["cmake_output_dir"])
    source_mk = target.get("source_mk") or target.get("_analysis_source")
    if not source_mk:
        raise SystemExit(f"target has no source_mk: {target.get('target_id')}")
    mk_path = pathlib.Path(source_mk)
    if not mk_path.is_absolute():
        mk_path = pathlib.Path(cfg["project_root"]) / mk_path
    return mk_path.parent


def ensure_cmake_dir(out: pathlib.Path) -> None:
    out.mkdir(parents=True, exist_ok=True)
    root = out / "CMakeLists.txt"
    if not root.exists():
        root.write_text(
            "# Generated by workflow_v2.\n"
            "# This file is intended to be included by the top-level project.\n"
            "# Do not add project() here; define the project in the root CMakeLists.txt.\n"
        )


def source_mk_path(cfg: dict, target: dict) -> pathlib.Path | None:
    source_mk = target.get("source_mk") or target.get("_analysis_source")
    if not source_mk:
        return None
    mk_path = pathlib.Path(source_mk)
    if not mk_path.is_absolute():
        mk_path = pathlib.Path(cfg["project_root"]) / mk_path
    return mk_path


def existing_child_cmake_lists(cfg: dict, target: dict, cmake_out: pathlib.Path) -> list[str]:
    mk_path = source_mk_path(cfg, target)
    if not mk_path:
        return []
    mk_dir = mk_path.parent
    rows = []
    for child in sorted(mk_dir.iterdir() if mk_dir.exists() else []):
        cmake_file = child / "CMakeLists.txt"
        if child.is_dir() and cmake_file.exists():
            try:
                rows.append(str(child.relative_to(cmake_out)))
            except ValueError:
                rows.append(str(child))
    return rows


def prompt_for(cfg: dict, target: dict, cmake_out: pathlib.Path) -> str:
    cmake_file = cmake_out / "CMakeLists.txt"
    child_cmake = existing_child_cmake_lists(cfg, target, cmake_out)
    return """# CMake Conversion Task

Convert this target JSON into CMake.

Output layout: `%s`
CMake output directory: `%s`
Primary generated file: `%s`
Existing direct child directories that already contain CMakeLists.txt:
```json
%s
```

Target JSON:
```json
%s
```

Requirements:

- Add a trace comment with `workflow_v2:target_id=...`.
- Preserve product conditions as real CMake `if(...)` logic.
- Only edit files inside the CMake output directory.
- Generate everything directly in `CMakeLists.txt`; do not create or include
  `generated_targets.cmake`.
- Do not add `project()`; the root CMakeLists.txt defines the project.
- For Makefile/Android.mk switches, use `if(SWITCH_NAME)` directly. The root
  CMake project is responsible for defining these variables.
- Implement conditional behavior completely. If the JSON contains
  `conditional_sources`, `conditional_defines`, `conditional_include_dirs`,
  `conditional_compile_options`, `conditional_link_libraries`, or
  `conditional_link_options`, generate real `if(...)` blocks with the matching
  target_* command: `target_sources`, `target_compile_definitions`,
  `target_include_directories`, `target_compile_options`,
  `target_link_libraries`, or `target_link_options`.
- Do not leave conditional behavior as comments only.
- If a switch variable is not defined in this directory, use it anyway. Do not
  create `option()` defaults, TODO comments, or fallback defaults for
  production switches.
- If generating `add_subdirectory(child)`, only use child directories listed in
  `Existing direct child directories that already contain CMakeLists.txt`.
""" % (
        output_layout(cfg),
        str(cmake_out),
        str(cmake_file),
        json.dumps(child_cmake, ensure_ascii=False, indent=2),
        json.dumps(target, ensure_ascii=False, indent=2),
    )


def convert_one(
    cfg: dict,
    target: dict,
    index: int,
    total: int,
    prompts_dir: pathlib.Path,
    results_dir: pathlib.Path,
    logs_dir: pathlib.Path,
    locks: dict[pathlib.Path, threading.Lock],
    locks_guard: threading.Lock,
) -> tuple[str, int, str]:
    target_id = target["target_id"]
    cmake_out = cmake_output_for_target(cfg, target)
    cmake_key = cmake_out.resolve()
    with locks_guard:
        lock = locks.setdefault(cmake_key, threading.Lock())

    # OpenCode edits CMakeLists.txt. Serialize tasks that target the same file.
    with lock:
        ensure_cmake_dir(cmake_out)
        progress(index, total, f"convert {target_id} -> {rel(cmake_out)}")
        prompt_path = prompts_dir / f"{target_id}.v2-cmake-converter.md"
        result_path = results_dir / f"{target_id}.v2-cmake-converter.out"
        stderr_path = logs_dir / f"{target_id}.v2-cmake-converter.err"
        write_text(prompt_path, prompt_for(cfg, target, cmake_out))
        cmd = [
            cfg["opencode_bin"],
            "run",
            "--agent",
            "v2-cmake-converter",
            "--model",
            cfg.get("model", "deepseek/deepseek-v4-pro"),
            "--file",
            str(prompt_path),
            "--",
            "Generate or update the CMake files for this target.",
        ]
        cp = run(cmd, cfg)
        write_text(result_path, cp.stdout)
        write_text(stderr_path, cp.stderr)
    message = (
        f"{target_id}: layout={output_layout(cfg)} cmake_dir={rel(cmake_out)} "
        f"returncode={cp.returncode} result={rel(result_path)}"
    )
    return target_id, cp.returncode, message


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("config")
    parser.add_argument("--limit", type=int, default=0, help="maximum number of targets to convert")
    parser.add_argument("-j", "--jobs", type=int, default=1, help="parallel OpenCode conversion jobs")
    args = parser.parse_args()
    if args.jobs < 1:
        raise SystemExit("--jobs must be >= 1")
    cfg = load_config(args.config)
    state = pathlib.Path(cfg["state_dir"])
    targets = read_jsonl(state / "targets.jsonl")
    if args.limit > 0:
        targets = targets[: args.limit]
    prompts_dir = state / "prompts"
    results_dir = state / "opencode_results"
    logs_dir = state / "logs"

    print(f"converting {len(targets)} target(s) with jobs={args.jobs}")
    locks: dict[pathlib.Path, threading.Lock] = {}
    locks_guard = threading.Lock()
    failures = 0
    with concurrent.futures.ThreadPoolExecutor(max_workers=args.jobs) as executor:
        futures = [
            executor.submit(
                convert_one,
                cfg,
                target,
                index,
                len(targets),
                prompts_dir,
                results_dir,
                logs_dir,
                locks,
                locks_guard,
            )
            for index, target in enumerate(targets, start=1)
        ]
        for future in concurrent.futures.as_completed(futures):
            _, returncode, message = future.result()
            print(message)
            if returncode != 0:
                failures += 1
    if failures:
        print(f"conversion finished with {failures} failed OpenCode run(s)")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
