#!/usr/bin/env python3
import json
import pathlib
import sys

from common import load_config, read_jsonl, rel, require_args, run, write_text


def ensure_root_cmake(cfg: dict) -> None:
    out = pathlib.Path(cfg["cmake_output_dir"])
    out.mkdir(parents=True, exist_ok=True)
    root = out / "CMakeLists.txt"
    if not root.exists():
        root.write_text(
            "cmake_minimum_required(VERSION 3.16)\n"
            "project(converted_subproject C CXX)\n\n"
            "set(CMAKE_EXPORT_COMPILE_COMMANDS ON)\n\n"
            "include(${CMAKE_CURRENT_LIST_DIR}/generated_targets.cmake OPTIONAL)\n"
        )
    generated = out / "generated_targets.cmake"
    if not generated.exists():
        generated.write_text("# Generated by workflow_v2.\n")


def prompt_for(cfg: dict, target: dict) -> str:
    return """# CMake Conversion Task

Convert this target JSON into CMake.

CMake output directory: `%s`
Primary generated file: `%s`

Target JSON:
```json
%s
```

Requirements:

- Add a trace comment with `workflow_v2:target_id=...`.
- Preserve product conditions as CMake options or comments.
- Only edit files inside the CMake output directory.
""" % (
        cfg["cmake_output_dir"],
        str(pathlib.Path(cfg["cmake_output_dir"]) / "generated_targets.cmake"),
        json.dumps(target, ensure_ascii=False, indent=2),
    )


def main() -> int:
    cfg = load_config(require_args(sys.argv, "usage: convert_targets.py <config.json>"))
    state = pathlib.Path(cfg["state_dir"])
    targets = read_jsonl(state / "targets.jsonl")
    prompts_dir = state / "prompts"
    results_dir = state / "opencode_results"
    logs_dir = state / "logs"
    ensure_root_cmake(cfg)

    for target in targets:
        target_id = target["target_id"]
        prompt_path = prompts_dir / f"{target_id}.v2-cmake-converter.md"
        result_path = results_dir / f"{target_id}.v2-cmake-converter.out"
        stderr_path = logs_dir / f"{target_id}.v2-cmake-converter.err"
        write_text(prompt_path, prompt_for(cfg, target))
        cmd = [
            cfg["opencode_bin"],
            "run",
            "--agent",
            "v2-cmake-converter",
            "--model",
            cfg.get("model", "deepseek/deepseek-v4-pro"),
            "--file",
            str(prompt_path),
            "--",
            "Generate or update the CMake files for this target.",
        ]
        cp = run(cmd, cfg)
        write_text(result_path, cp.stdout)
        write_text(stderr_path, cp.stderr)
        print(f"{target_id}: returncode={cp.returncode} result={rel(result_path)}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())

