#!/usr/bin/env python3
import argparse
import concurrent.futures
import json
import pathlib
import tempfile
import threading

from common import (
    TIMEOUT_RETURNCODE,
    analysis_result_path,
    cmake_path_for_mk,
    load_config,
    log_path,
    now,
    progress,
    read_jsonl,
    rel,
    resolve_path,
    run,
    write_text,
)
from excel_board import (
    COL_ANALYSIS_RESULT,
    COL_ANALYSIS_STATUS,
    COL_CMAKE_PATH,
    COL_CONVERSION_DONE,
    COL_CONVERSION_OK,
    COL_CONVERSION_RETURN,
    COL_CONVERSION_STATUS,
    COL_CONVERSION_STDERR,
    COL_CONVERSION_STDOUT,
    COL_CONVERSION_UPDATED,
    COL_MANUAL_COMMENT,
    COL_MK_PATH,
    COL_RETRY_COUNT,
    COL_TASK_ID,
    active_manual_comment,
    load_board,
    mutate_board,
    row_by_path,
    yes_no,
)


def normalize_mk_path(cfg: dict, value: str) -> str:
    root = pathlib.Path(cfg["project_root"])
    path = pathlib.Path(value)
    if not path.is_absolute():
        path = root / path
    path = path.resolve()
    if not path.exists() or not path.is_file():
        raise SystemExit(f"mk/makefile path does not exist: {value}")
    return rel(path, root)


def read_file_list(path: str) -> list[str]:
    rows = []
    with pathlib.Path(path).open(encoding="utf-8") as f:
        for raw in f:
            line = raw.strip()
            if line and not line.startswith("#"):
                rows.append(line)
    return rows


def selected_rows(cfg: dict, rows: list[dict[str, str]], args: argparse.Namespace) -> list[dict[str, str]]:
    manual = list(args.mk_file or [])
    for list_path in args.file_list or []:
        manual.extend(read_file_list(list_path))
    if not manual:
        return rows

    wanted = {normalize_mk_path(cfg, value) for value in manual}
    by_path = row_by_path(rows)
    missing = sorted(path for path in wanted if path not in by_path)
    if missing:
        raise SystemExit("these paths are not in the Excel board; run discover first: " + ", ".join(missing))
    return [by_path[path] for path in sorted(wanted)]


def analysis_ready(row: dict[str, str]) -> bool:
    return row.get(COL_ANALYSIS_STATUS) in {"done", "empty"}


def cmake_has_trace(cmake_file: pathlib.Path, task_id: str) -> bool:
    if not cmake_file.exists():
        return False
    return f"workflow_v3:mk_task_id={task_id}" in cmake_file.read_text(errors="replace")


def conversion_success(row: dict[str, str], cfg: dict) -> bool:
    if row.get(COL_ANALYSIS_STATUS) == "empty":
        return row.get(COL_CONVERSION_STATUS) == "no_targets"
    if row.get(COL_CONVERSION_STATUS) != "done":
        return False
    return cmake_has_trace(cmake_path_for_mk(cfg, row[COL_MK_PATH]), row[COL_TASK_ID])


def rows_needing_conversion(rows: list[dict[str, str]], cfg: dict, force: bool, only_commented: bool) -> list[dict[str, str]]:
    selected = []
    for row in rows:
        if not analysis_ready(row):
            continue
        manual = active_manual_comment(row.get(COL_MANUAL_COMMENT, ""))
        if only_commented and not manual:
            continue
        if force or manual or not conversion_success(row, cfg):
            selected.append(row)
    return selected


def existing_child_cmake_lists(cfg: dict, mk_rel_path: str, cmake_file: pathlib.Path) -> list[str]:
    root = pathlib.Path(cfg["project_root"])
    mk_dir = (root / mk_rel_path).parent
    rows = []
    for child in sorted(mk_dir.iterdir() if mk_dir.exists() else []):
        child_cmake = child / "CMakeLists.txt"
        if child.is_dir() and child_cmake.exists():
            try:
                rows.append(str(child.relative_to(cmake_file.parent)))
            except ValueError:
                rows.append(str(child))
    return rows


def ensure_cmake_file(path: pathlib.Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if not path.exists():
        path.write_text(
            "# Generated by workflow_v3.\n"
            "# This file is intended to be included by the outer root CMake project.\n"
            "# Do not add project() here.\n\n",
            encoding="utf-8",
        )


def prompt_for(cfg: dict, row: dict[str, str], targets: list[dict], manual_comment: str) -> str:
    cmake_file = cmake_path_for_mk(cfg, row[COL_MK_PATH])
    manual_section = ""
    if manual_comment.strip():
        manual_section = """
Human review comment from the Excel board:
```text
%s
```
Regenerate or update the CMake for this primary mk according to this comment.
""" % manual_comment.strip()

    return """# workflow_v3 CMake Conversion Task

Convert all target JSON records for one primary Makefile/Android.mk/*.mk file
into the single CMakeLists.txt beside that mk file.

Primary mk path: `%s`
CMake output file: `%s`
Existing direct child directories that already contain CMakeLists.txt:
```json
%s
```

Target JSON records:
```json
%s
```
%s

Requirements:

- Only create or modify this file: `%s`.
- Do not modify original Makefile/Android.mk/*.mk files.
- Do not create `generated_targets.cmake` or any other generated CMake include.
- Do not call `project()`. The outer root CMake project owns `project()`.
- Add one trace comment for this primary mk:
  `# workflow_v3:mk_task_id=%s source_mk=%s`
- If updating an existing block with the same trace, replace that block instead
  of duplicating it.
- Prefer target-level CMake commands: `add_library`, `add_executable`,
  `target_sources`, `target_include_directories`,
  `target_compile_definitions`, `target_compile_options`,
  `target_link_libraries`, and `target_link_options`.
- Preserve Makefile/Android.mk switch conditions as real CMake `if(...)`
  logic. Do not leave conditional sources, defines, include dirs, flags, or
  link items as comments only.
- Use switch variables directly even if they are not defined in this directory.
  The outer root CMake project defines production switches.
- Do not generate conditions from workflow product names. workflow_v3 does not
  pass product names to this prompt.
- For `include_aggregator` records, do not generate libraries or executables.
  Generate conservative aggregation logic. Use `add_subdirectory(child)` only
  when `child` is listed in the existing child CMakeLists list above. Otherwise
  leave a short CMake comment describing the skipped aggregation.
- Never pass unexpanded wildcard paths to `add_library`, `add_executable`, or
  `target_sources`. CMake target commands do not expand `*`, `?`, `[]`, or
  `**`.
- Prefer explicit source file lists. If a JSON source is still a wildcard and
  concrete files are visible in the repository, expand it. Only as a last
  resort use `file(GLOB CONFIGURE_DEPENDS ...)` and pass the resulting variable
  to `target_sources`, with a comment naming the original Makefile wildcard.
- Do not put wildcard include dirs in `target_include_directories`.
- Do not put wildcard libraries in `target_link_libraries`.
- Do not put unresolved Makefile expressions such as `$(LOCAL_PATH)/foo.c` or
  `$(call ...)` into `target_sources`. Resolve them or omit them with a concise
  risk comment.

Return a concise Markdown summary of the CMake file changed and any unresolved
risks.
""" % (
        row[COL_MK_PATH],
        str(cmake_file),
        json.dumps(existing_child_cmake_lists(cfg, row[COL_MK_PATH], cmake_file), ensure_ascii=False, indent=2),
        json.dumps(targets, ensure_ascii=False, indent=2),
        manual_section,
        str(cmake_file),
        row[COL_TASK_ID],
        row[COL_MK_PATH],
    )


def write_temp_prompt(cfg: dict, task_id: str, text: str) -> pathlib.Path:
    tmp_dir = pathlib.Path(cfg["state_dir"]) / "tmp"
    tmp_dir.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile("w", encoding="utf-8", delete=False, dir=str(tmp_dir), prefix=f"{task_id}.", suffix=".prompt.md") as f:
        f.write(text)
        return pathlib.Path(f.name)


def result_targets(cfg: dict, row: dict[str, str]) -> list[dict]:
    result = row.get(COL_ANALYSIS_RESULT) or rel(analysis_result_path(cfg, row[COL_TASK_ID]))
    return read_jsonl(resolve_path(result))


def convert_one(
    cfg: dict,
    row: dict[str, str],
    index: int,
    total: int,
    timeout: int,
    locks: dict[pathlib.Path, threading.Lock],
    locks_guard: threading.Lock,
) -> dict:
    task_id = row[COL_TASK_ID]
    mk_path = row[COL_MK_PATH]
    cmake_file = cmake_path_for_mk(cfg, mk_path)
    stdout_path = log_path(cfg, f"{task_id}.conversion", "out")
    stderr_path = log_path(cfg, f"{task_id}.conversion", "err")

    targets = result_targets(cfg, row)
    if not targets:
        return {
            "mk_path": mk_path,
            "task_id": task_id,
            "status": "no_targets",
            "returncode": 0,
            "stdout_log": "",
            "stderr_log": "",
            "manual_comment": row.get(COL_MANUAL_COMMENT, ""),
            "message": f"{mk_path}: no analysis targets; conversion marked no_targets",
        }

    with locks_guard:
        lock = locks.setdefault(cmake_file.resolve(), threading.Lock())

    with lock:
        ensure_cmake_file(cmake_file)
        prompt = write_temp_prompt(cfg, task_id, prompt_for(cfg, row, targets, row.get(COL_MANUAL_COMMENT, "")))
        progress(index, total, f"convert {mk_path} -> {rel(cmake_file)}")
        try:
            cmd = [
                cfg["opencode_bin"],
                "run",
                "--agent",
                "v3-cmake-converter",
                "--model",
                cfg["model"],
                "--file",
                str(prompt),
                "--",
                "Generate or update the CMakeLists.txt for this primary mk.",
            ]
            cp = run(cmd, cfg, timeout=timeout)
        finally:
            prompt.unlink(missing_ok=True)

        write_text(stdout_path, cp.stdout)
        write_text(stderr_path, cp.stderr)

    if cp.returncode == TIMEOUT_RETURNCODE:
        status = "timeout"
    elif cp.returncode != 0:
        status = "failed"
    elif not cmake_has_trace(cmake_file, task_id):
        status = "failed_no_trace"
    else:
        status = "done"

    return {
        "mk_path": mk_path,
        "task_id": task_id,
        "status": status,
        "returncode": cp.returncode if status != "failed_no_trace" else 2,
        "stdout_log": rel(stdout_path),
        "stderr_log": rel(stderr_path),
        "manual_comment": row.get(COL_MANUAL_COMMENT, ""),
        "message": f"{mk_path}: status={status} returncode={cp.returncode} cmake={rel(cmake_file)}",
    }


def update_board_row(cfg: dict, status_row: dict) -> None:
    board_path = pathlib.Path(cfg["board_path"])

    def update(headers: list[str], rows: list[dict[str, str]]):
        by_path = row_by_path(rows)
        row = by_path.get(status_row["mk_path"])
        if row is None:
            return headers, rows

        status = status_row["status"]
        ok = status in {"done", "no_targets"}
        row[COL_CMAKE_PATH] = rel(cmake_path_for_mk(cfg, row[COL_MK_PATH]), pathlib.Path(cfg["project_root"]))
        row[COL_CONVERSION_STATUS] = status
        row[COL_CONVERSION_DONE] = yes_no(ok)
        row[COL_CONVERSION_OK] = yes_no(ok)
        row[COL_CONVERSION_RETURN] = str(status_row["returncode"])
        row[COL_CONVERSION_STDOUT] = status_row["stdout_log"]
        row[COL_CONVERSION_STDERR] = status_row["stderr_log"]
        row[COL_CONVERSION_UPDATED] = now()
        retries = int(row.get(COL_RETRY_COUNT, "0") or "0")
        row[COL_RETRY_COUNT] = str(retries + 1 if status != "no_targets" else retries)

        old_comment = status_row.get("manual_comment", "")
        if ok and active_manual_comment(old_comment):
            row[COL_MANUAL_COMMENT] = "已完成：" + old_comment
        return headers, rows

    mutate_board(board_path, update)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("config")
    parser.add_argument("--limit", type=int, default=0, help="maximum number of rows to convert")
    parser.add_argument("-j", "--jobs", type=int, default=1, help="parallel OpenCode conversion jobs")
    parser.add_argument("--timeout", type=int, default=0, help="per-OpenCode timeout seconds")
    parser.add_argument("--force", action="store_true", help="rerun selected rows even if conversion is already successful")
    parser.add_argument("--only-commented", action="store_true", help="only convert rows with active human comments")
    parser.add_argument("--mk-file", action="append", default=[], help="specific mk/makefile path from the Excel board; repeatable")
    parser.add_argument("--file-list", "--mk-list", action="append", default=[], help="text file of mk/makefile paths; repeatable")
    args = parser.parse_args()
    if args.jobs < 1:
        raise SystemExit("--jobs must be >= 1")

    cfg = load_config(args.config)
    timeout = args.timeout or int(cfg.get("conversion_opencode_timeout_seconds", cfg.get("opencode_timeout_seconds", 1800)))
    _, board_rows = load_board(cfg["board_path"])
    if not board_rows:
        raise SystemExit(f"Excel board is empty or missing; run discover and analyze first: {cfg['board_path']}")

    candidates = selected_rows(cfg, board_rows, args)
    tasks = rows_needing_conversion(candidates, cfg, args.force, args.only_commented)
    if args.limit > 0:
        tasks = tasks[: args.limit]

    skipped_not_ready = len([row for row in candidates if not analysis_ready(row)])
    print(
        f"conversion board={rel(cfg['board_path'])}; selected={len(candidates)}; "
        f"to_run={len(tasks)}; skipped_not_analyzed={skipped_not_ready}; "
        f"jobs={args.jobs}; timeout={timeout}s; force={args.force}; only_commented={args.only_commented}",
        flush=True,
    )
    if not tasks:
        return 0

    failures = 0
    locks: dict[pathlib.Path, threading.Lock] = {}
    locks_guard = threading.Lock()
    with concurrent.futures.ThreadPoolExecutor(max_workers=args.jobs) as executor:
        futures = [
            executor.submit(convert_one, cfg, row, index, len(tasks), timeout, locks, locks_guard)
            for index, row in enumerate(tasks, start=1)
        ]
        for future in concurrent.futures.as_completed(futures):
            status_row = future.result()
            update_board_row(cfg, status_row)
            print(status_row["message"], flush=True)
            if status_row["status"] not in {"done", "no_targets"}:
                failures += 1

    if failures:
        print(f"conversion finished with {failures} failed/timeout task(s)", flush=True)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
